services:
  - type: web
    name: starship-admin
    env: node
    buildCommand: npm install
    startCommand: npm run start:admin
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: worker
    name: starship-bot
    env: node
    buildCommand: npm install
    startCommand: npm run start:bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CRYPTO_BOT_TOKEN
        sync: false 